- name: Read the dictionary file
  include_vars:
    file: "{{ role_path }}/dictionary.yaml"

- name: Creating directory for flexget
  ansible.builtin.file:
    path: "~/flexget"
    state: directory
    mode: '0777'

- name: Render the docker-compose template
  template:
    src: docker-compose.yaml.j2
    dest: "~/flexget/docker-compose.yml"
