- name: Read the dictionary file
  include_vars:
    file: "{{ role_path }}/dictionary.yaml"

- name: Creating directory for wireguard
  ansible.builtin.file:
    path: "{{config}}"
    state: directory
    mode: '0777'

- name: Render the docker-compose template
  template:
    src: docker-compose.yaml.j2
    dest: "{{config}}/docker-compose.yml"