- name: Read the dictionary file
  include_vars:
    file: "{{ role_path }}/dictionary.yaml"

- name: Creating directory for plex
  ansible.builtin.file:
    path: "~/plex"
    state: directory
    mode: '0777'

- name: Render the docker-compose template
  template:
    src: docker-compose.yaml.j2
    dest: "~/plex/docker-compose.yml"

